export const jobRoles = [
  // ========== SOFTWARE DEVELOPMENT ==========
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Software Engineer",
  "Senior Software Engineer",
  "Lead Software Engineer",
  "Software Architect",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "React Developer",
  "Angular Developer",
  "Vue.js Developer",
  "Node.js Developer",
  "Python Developer",
  "Java Developer",
  "C++ Developer",
  ".NET Developer",
  "PHP Developer",
  "Ruby on Rails Developer",
  "Go Developer",
  "Rust Developer",
  "Game Developer",
  "Unity Developer",
  "Unreal Engine Developer",
  "Embedded Systems Engineer",
  "Firmware Engineer",

  // ========== DEVOPS & INFRASTRUCTURE ==========
  "DevOps Engineer",
  "Site Reliability Engineer (SRE)",
  "Cloud Engineer",
  "Cloud Architect",
  "AWS Engineer",
  "Azure Engineer",
  "GCP Engineer",
  "Platform Engineer",
  "Infrastructure Engineer",
  "System Administrator",
  "Network Engineer",
  "Network Architect",
  "Security Engineer",
  "DevSecOps Engineer",
  "Kubernetes Engineer",
  "Docker Specialist",

  // ========== DATA & ANALYTICS ==========
  "Data Scientist",
  "Data Analyst",
  "Business Intelligence Analyst",
  "Data Engineer",
  "Big Data Engineer",
  "Machine Learning Engineer",
  "AI Engineer",
  "Deep Learning Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "MLOps Engineer",
  "Research Scientist",
  "Quantitative Analyst",
  "Analytics Manager",
  "Data Architect",
  "ETL Developer",

  // ========== CYBERSECURITY ==========
  "Cybersecurity Analyst",
  "Information Security Analyst",
  "Security Architect",
  "Penetration Tester",
  "Ethical Hacker",
  "Security Operations Center (SOC) Analyst",
  "Incident Response Analyst",
  "Compliance Analyst",
  "Risk Analyst",
  "Cryptographer",

  // ========== QA & TESTING ==========
  "QA Engineer",
  "Quality Assurance Analyst",
  "Test Engineer",
  "Automation Test Engineer",
  "Manual Tester",
  "Performance Test Engineer",
  "SDET (Software Development Engineer in Test)",

  // ========== DESIGN & CREATIVE ==========
  "UI/UX Designer",
  "Product Designer",
  "User Experience Designer",
  "User Interface Designer",
  "Interaction Designer",
  "Visual Designer",
  "Graphic Designer",
  "Web Designer",
  "Motion Graphics Designer",
  "3D Designer",
  "Brand Designer",
  "Creative Director",
  "Art Director",
  "Illustrator",
  "Video Editor",
  "Animator",
  "Game Designer",

  // ========== PRODUCT MANAGEMENT ==========
  "Product Manager",
  "Senior Product Manager",
  "Lead Product Manager",
  "Associate Product Manager",
  "Technical Product Manager",
  "Product Owner",
  "Chief Product Officer",
  "Product Analyst",
  "Product Designer",
  "Growth Product Manager",

  // ========== PROJECT MANAGEMENT ==========
  "Project Manager",
  "Technical Project Manager",
  "Program Manager",
  "Scrum Master",
  "Agile Coach",
  "PMO Manager",
  "Delivery Manager",
  "Release Manager",

  // ========== MARKETING ==========
  "Digital Marketing Manager",
  "Marketing Manager",
  "Content Marketing Manager",
  "Social Media Manager",
  "SEO Specialist",
  "SEM Specialist",
  "Email Marketing Specialist",
  "Marketing Analyst",
  "Brand Manager",
  "Growth Marketing Manager",
  "Performance Marketing Manager",
  "Affiliate Marketing Manager",
  "Influencer Marketing Manager",
  "Marketing Coordinator",
  "Marketing Director",
  "Chief Marketing Officer (CMO)",
  "Copywriter",
  "Content Writer",
  "Technical Writer",
  "Content Strategist",

  // ========== SALES & BUSINESS DEVELOPMENT ==========
  "Sales Manager",
  "Sales Executive",
  "Account Executive",
  "Business Development Manager",
  "Business Development Representative (BDR)",
  "Sales Development Representative (SDR)",
  "Account Manager",
  "Customer Success Manager",
  "Sales Engineer",
  "Solutions Architect",
  "Regional Sales Manager",
  "Director of Sales",
  "VP of Sales",
  "Chief Revenue Officer (CRO)",
  "Inside Sales Representative",
  "Outside Sales Representative",

  // ========== CUSTOMER SUCCESS & SUPPORT ==========
  "Customer Success Manager",
  "Customer Support Specialist",
  "Technical Support Engineer",
  "Support Engineer",
  "Help Desk Technician",
  "Customer Experience Manager",
  "Client Relations Manager",
  "Customer Service Representative",

  // ========== HUMAN RESOURCES ==========
  "HR Manager",
  "Human Resources Manager",
  "HR Business Partner",
  "Recruiter",
  "Technical Recruiter",
  "Talent Acquisition Specialist",
  "Talent Acquisition Manager",
  "HR Generalist",
  "Compensation and Benefits Manager",
  "Learning and Development Manager",
  "Training Coordinator",
  "Employee Relations Manager",
  "HR Director",
  "Chief Human Resources Officer (CHRO)",
  "People Operations Manager",

  // ========== OPERATIONS ==========
  "Operations Manager",
  "Operations Analyst",
  "Business Operations Manager",
  "Supply Chain Manager",
  "Logistics Manager",
  "Warehouse Manager",
  "Inventory Manager",
  "Procurement Manager",
  "Facilities Manager",
  "Chief Operating Officer (COO)",

  // ========== FINANCE & ACCOUNTING ==========
  "Financial Analyst",
  "Senior Financial Analyst",
  "Accountant",
  "Senior Accountant",
  "Staff Accountant",
  "Tax Accountant",
  "Management Accountant",
  "Cost Accountant",
  "Auditor",
  "Internal Auditor",
  "External Auditor",
  "Finance Manager",
  "Accounting Manager",
  "Controller",
  "Financial Controller",
  "Chief Financial Officer (CFO)",
  "Treasurer",
  "Financial Planning and Analysis (FP&A) Manager",
  "Budget Analyst",
  "Payroll Specialist",
  "Accounts Payable Specialist",
  "Accounts Receivable Specialist",
  "Bookkeeper",
  "Investment Analyst",
  "Portfolio Manager",

  // ========== LEGAL & COMPLIANCE ==========
  "Legal Counsel",
  "Corporate Lawyer",
  "Contract Manager",
  "Compliance Officer",
  "Compliance Manager",
  "Legal Assistant",
  "Paralegal",
  "Intellectual Property Lawyer",
  "General Counsel",
  "Chief Legal Officer",

  // ========== EXECUTIVE & LEADERSHIP ==========
  "Chief Executive Officer (CEO)",
  "Chief Technology Officer (CTO)",
  "Chief Information Officer (CIO)",
  "Chief Data Officer (CDO)",
  "Chief Security Officer (CSO)",
  "Managing Director",
  "Vice President",
  "Director",
  "Department Head",

  // ========== CONSULTING ==========
  "Management Consultant",
  "Strategy Consultant",
  "IT Consultant",
  "Business Analyst",
  "Systems Analyst",
  "Process Analyst",
  "Change Management Consultant",

  // ========== HEALTHCARE (Tech Adjacent) ==========
  "Healthcare Data Analyst",
  "Clinical Data Manager",
  "Medical Software Engineer",
  "Biomedical Engineer",
  "Health Informatics Specialist",

  // ========== EDUCATION & TRAINING ==========
  "Corporate Trainer",
  "Instructional Designer",
  "E-Learning Developer",
  "Training Manager",
  "Education Program Manager",

  // ========== REAL ESTATE ==========
  "Real Estate Agent",
  "Property Manager",
  "Real Estate Analyst",
  "Commercial Real Estate Broker",

  // ========== RETAIL & E-COMMERCE ==========
  "E-Commerce Manager",
  "Merchandising Manager",
  "Retail Manager",
  "Store Manager",
  "Category Manager",

  // ========== HOSPITALITY & TOURISM ==========
  "Hotel Manager",
  "Restaurant Manager",
  "Event Manager",
  "Catering Manager",

  // ========== MANUFACTURING & ENGINEERING ==========
  "Mechanical Engineer",
  "Electrical Engineer",
  "Civil Engineer",
  "Industrial Engineer",
  "Chemical Engineer",
  "Manufacturing Engineer",
  "Process Engineer",
  "Quality Engineer",
  "Production Manager",
  "Plant Manager",

  // ========== MEDIA & COMMUNICATIONS ==========
  "Public Relations Manager",
  "Communications Manager",
  "Journalist",
  "Editor",
  "Content Producer",
  "Podcast Producer",
  "Social Media Coordinator",

  // ========== RESEARCH & DEVELOPMENT ==========
  "Research and Development Engineer",
  "R&D Manager",
  "Laboratory Technician",
  "Research Associate",

  // ========== OTHER ==========
  "Intern",
  "Entry Level",
  "Graduate Trainee",
  "Administrative Assistant",
  "Executive Assistant",
  "Office Manager",
  "Receptionist",
  "Other",
];
